[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.20.2"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.20.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.20.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.20.2"

[[override]]
  name = "k8s.io/kube-scheduler"
  version = "kubernetes-1.20.2"

[[override]]
  name = "k8s.io/component-base"
  version = "kubernetes-1.20.2"

[[constraint]]
  name = "k8s.io/kubernetes"
  # 1.20.2
  revision = "faecb196815e248d3ecfb03c680a4507229c2a56"

[[constraint]]
  name = "k8s.io/utils"
  revision = "d5654de09c73da55eb19ae4ab4f734f7a61747a6"

[[override]]
  name = "k8s.io/klog"
  source = "github.com/ingvagabund/klog"
  branch = "k8s-1.20.2"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "v1.7.1"

[[override]]
  name = "sigs.k8s.io/structured-merge-diff"
  # temporary solution until scheduler framework is fully migrate to a seperate community repository
  source = "github.com/ingvagabund/structured-merge-diff"
  branch = "k8s-1.20.2"

[[override]]
  name = "github.com/cespare/xxhash"
  # temporary solution until scheduler framework is fully migrate to a seperate community repository
  source = "github.com/ingvagabund/xxhash"
  branch = "kubernetes-1.19.0-rc.4"

[[override]]
  name = "github.com/googleapis/gnostic"
  revision = "v0.4.1"

[[override]]
  name = "k8s.io/kube-openapi"
  # Nov 13, 2020
  revision = "d219536bb9fd63731fa65ca4b42f14bc2f10c61b"

[[override]]
  name = "k8s.io/csi-translation-lib"
  version = "kubernetes-1.20.2"

[[override]]
  name = "k8s.io/cloud-provider"
  version = "kubernetes-1.20.2"

[[override]]
  name = "github.com/coreos/etcd"
  revision = "v3.3.10"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "kubernetes-1.20.2"

[[override]]
  name = "google.golang.org/grpc"
  revision = "v1.27.0"

[[override]]
  name = "golang.org/x/text"
  version = "v0.3.3"

[[override]]
  name = "golang.org/x/net"
  revision = "69a78807bb2bb6d1599c68698c6b009505012083"

[[override]]
  name = "github.com/gogo/protobuf"
  # Fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121
  version = "v1.3.2"

[prune]
  go-tests = true
  unused-packages = true
